# Generated by Django 3.2.16 on 2022-10-25 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_event_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_location', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['seat_location'],
            },
        ),
        migrations.CreateModel(
            name='EventSeating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserved_on', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.event')),
                ('reserved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_seats', to=settings.AUTH_USER_MODEL)),
                ('seat_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_seating', to='seating.venueseat')),
            ],
            options={
                'ordering': ['-reserved_on'],
                'unique_together': {('event', 'seat_location')},
            },
        ),
    ]
