# Generated by Django 3.2.16 on 2022-10-31 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseating',
            name='seat_location_1',
            field=models.ForeignKey(default='88ea3d20-4288-46d9-9904-3bb39056bf10', on_delete=django.db.models.deletion.CASCADE, related_name='event_seating_1', to='seating.venueseat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventseating',
            name='seat_location_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_seating_2', to='seating.venueseat'),
        ),
        migrations.AlterUniqueTogether(
            name='eventseating',
            unique_together={('event', 'reserved_by')},
        ),
        migrations.RemoveField(
            model_name='eventseating',
            name='seat_location',
        ),
    ]
